name: micro_dart_compiler
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  _fe_analyzer_shared: any
  kernel: any
  package_config: any

  micro_dart_runtime: 
    path: ../micro_dart_runtime
 
dev_dependencies:
  test: 1.21.4
  micro_dart_proxy_core: 
    path: ../micro_dart_proxy_core

 
  
dependency_overrides:
  _fe_analyzer_shared:
    path: ../../dart_sdk/sdk/pkg/_fe_analyzer_shared
  _js_interop_checks:
    path: ../../dart_sdk/sdk/pkg/_js_interop_checks
  front_end:
    path: ../../dart_sdk/sdk/pkg/front_end
  build_integration:
    path: ../../dart_sdk/sdk/pkg/build_integration
  frontend_server:
    path: ../../dart_sdk/sdk/pkg/frontend_server
  compiler:
    path: ../../dart_sdk/sdk/pkg/compiler
  dev_compiler:
    path: ../../dart_sdk/sdk/pkg/dev_compiler
  js_shared:
    path: ../../dart_sdk/sdk/pkg/js_shared
  js_runtime:
    path: ../../dart_sdk/sdk/pkg/js_runtime
  js_ast:
    path: ../../dart_sdk/sdk/pkg/js_ast
  meta:
    path: ../../dart_sdk/sdk/pkg/meta
  vm:
    path: ../../dart_sdk/sdk/pkg/vm
  kernel:
    path: ../../dart_sdk/sdk/pkg/kernel
  dart2js_info:
    path: ../../dart_sdk/sdk/pkg/dart2js_info
  analyzer:
    path: ../../dart_sdk/sdk/pkg/analyzer
  test:
    path: ../../dart_sdk/sdk/third_party/pkg/test/pkgs/test
  micro_dart_runtime:
    path: ../micro_dart_runtime
  micro_dart_proxy_core: 
    path: ../micro_dart_proxy_core
